version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "04:00"
  open-pull-requests-limit: 10
  
