version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
        versions:
          - 1.5.0-native-mt
          - 1.5.1-native-mt
      # Versions follow the Postgres version and should be updated manually
      - dependency-name: io.zonky.test.postgres:embedded-postgres-binaries-bom
