apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-se-bakover
   namespace: default
   labels:
      team: supstonad
spec:
   image: {{ image }}
   ingresses:
      - {{ ingress }}
   env:
     {{#each env}}
         - name: {{@key}}
      value: "{{this}}"
      {{/each}}
