apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-se-bakover
   namespace: default
   labels:
      team: supstonad
spec:
   image: {{ image }}
   ingresses:
      - {{ ingress }}
   vault:
      enabled: true
      paths:
         - mountPath: /var/run/secrets/nais.io/vault
           kvPath: /secret/supstonad/{{ secret_env }}
         - mountPath: /var/run/secrets/nais.io/vault/su-se-bakover
           kvPath: /kv/{{ cluster }}/fss/su-se-bakover/default
   env:
      {{#each env}}
       - name: {{@key}}
         value: "{{this}}"
      {{/each}}
