apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: su-se-bakover
  namespace: supstonad
  labels:
    team: supstonad
spec:
  azure:
    application:
      enabled: true
      tenant: {{ tenant }}
      replyURLs:
        - "http://localhost:8080/callback"
        - {{ env.BACKEND_CALLBACK_URL }}
  accessPolicy:
    inbound:
      rules:
        - application: su-se-framover
  image: {{ image }}
  liveness:
    path: /isalive
    initialDelay: 20
  readiness:
    path: /isready
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ ingress }}
  webproxy: true
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: {{ kafka-pool }}
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /secret/supstonad/{{ secret_env }}
      - mountPath: /var/run/secrets/nais.io/vault/su-se-bakover
        kvPath: /kv/{{ cluster }}/fss/su-se-bakover/default
      - mountPath: /var/run/secrets/nais.io/srvuser
        kvPath: /serviceuser/data/{{ secret_env }}/srvsupstonad
  env:
     {{#each env}}
      - name: {{@key}}
        value: "{{this}}"
     {{/each}}
