name: 'Deploy'
description: 'Deploy'

inputs:
  environment:
    required: true
    description: 'dev or prod'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: ${{ inputs.environment }}-fss
        RESOURCE: nais.yml
        VARS: nais-${{ inputs.environment }}.json
