#    permissions:
#      contents: 'write' # needed to create/edit releases
#      pull-requests: 'write' # needed to add labels to pull requests

name: 'Genereate draft release'
description: 'Appends all PR desctiptions to a draft release (creates/edits). Also adds labels to PRs'

inputs:
  GITHUB_TOKEN:
    description: 'The GitHub token to use for authentication'
    required: true
runs:
  using: "composite"
  steps:
    - uses: release-drafter/release-drafter@v5
      with:
        token: ${{ inputs.GITHUB_TOKEN }}

#  generate-draft-release:
#    name: Generate/update draft release
#    runs-on: ubuntu-latest
#    permissions:
#      contents: 'write' # needed to create/edit releases
#      pull-requests: 'write' # needed to add labels to pull requests
#    steps:
#      # Drafts your next Release notes as Pull Requests are merged into "master"
#      - uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}