name: 'Build and test'
description: 'Checkout, download java and assemble and test'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-java
    - name: Run gradle assemble
      uses: gradle/gradle-build-action@v2.8.0
      with:
        gradle-version: wrapper
        arguments: build
