name: 'Push image'
description: 'Push image'

inputs:
  identity_provider:
    required: true
    description: 'secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER'
  project_id:
    required: true
    description: 'vars.NAIS_MANAGEMENT_PROJECT_ID'
  tag:
    required: true
    description: 'github.sha'
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: supstonad
        tag: ${{ inputs.tag }}
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}



#      - uses: actions/checkout@v3
#      - name: Login to DockerHub
#        uses: docker/login-action@v2.2.0
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and publish Docker image
#        uses: docker/build-push-action@v4.1.1
#        with:
#          context: .
#          push: true
#          pull: true
#          tags: ${{env.IMAGE}}