name: gradle build test
description: bygger og tester. Denne skal brukes i 95% av casene.

inputs:
  token:
    description: github secret tokenet. send inn tokene som #${{ secrets.GITHUB_TOKEN }}
    required: true
  run:
    description: command that you want to run instead of the default
    required: false

runs:
  using: "composite"
  steps:
    - name: test and build with default
      shell: bash
      if: ${{inputs.run == ''}}
      run: ./gradlew test build
    - name: builds and tests with passed arguments
      shell: bash
      if: ${{inputs.run != ''}}
      run: ${{inputs.run}}
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ inputs.token }}