name: Build and deploy branches manually. See https://github.com/navikt/su-se-bakover/actions
# If you want to deploy a branch (feature branch or even redeploy master/main) to dev-fss (preprod) we use github actions workflow_dispatch
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
on: workflow_dispatch

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/su-se-bakover:${{ github.sha }}

jobs:
   build:
      name: Gradle test build and conditional docker build push
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v1
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle.kts') }}
            restore-keys: |
              ${{ runner.os }}-gradle-cache-
        - uses: actions/cache@v1
          with:
            path: ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-wrapper-
        - uses: actions/setup-java@v1
          with:
            java-version: '15.x'
        - name: test and build
          run: ./gradlew test build
          env:
            ORG_GRADLE_PROJECT_githubUser: x-access-token
            ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and publish Docker image
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            docker build --pull --tag ${IMAGE} .
            docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
            docker push ${IMAGE}

   deploy_to_dev:
      name: Deploy branch to dev-fss
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: nais/deploy/actions/deploy@v1
          env:
             APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
             CLUSTER: dev-fss
             RESOURCE: nais.yml
             VARS: nais-dev.json
