name: Deploy branch to dev-fss [manual deploy]
# If you want to deploy a branch (feature branch or even redeploy master/main) to dev-fss (preprod) we use github actions workflow_dispatch
# Goto https://github.com/navikt/su-se-bakover/actions/workflows/branch-deploy.yml choose a branch and deploy it
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
on: workflow_dispatch

env:
  IMAGE: ghcr.io/${{ github.repository }}/su-se-bakover:${{ github.sha }}

jobs:
  verify-master-is-ancestor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: | # git merge-base returns 0 when master is ancestor, 1 if it is not (other positive numbers on error)
          set +e
          origin_master="$(git rev-parse origin/master)"
          head="$(git rev-parse HEAD)"
          echo "Hash for origin master: ${origin_master}. Hash for HEAD: ${head}."
          merge_base="$(git merge-base $origin_master HEAD)"
          echo "Merge-base: ${merge_base}"
          git merge-base --is-ancestor $origin_master HEAD
          return_code=$?
          echo "Return code of 'git merge-base': ${return_code}"
          if [[ return_code -gt 0 ]]; then
            echo "You have to merge origin/master before you can deploy a branch."
            exit 1
          fi

  build:
    needs: verify-master-is-ancestor
    uses: navikt/su-se-bakover/.github/workflows/build.yml@main
    with:
      repo: ${{ github.repository }}
      token: ${{ secrets.GITHUB_TOKEN }}
      image: ${{env.IMAGE}}

  deploy_to_dev:
    needs: build
    uses: navikt/su-se-bakover/.github/workflows/dev-deploy.yml@main
    with:
      apikey: ${{ secrets.NAIS_DEPLOY_APIKEY }}
