on:
  push:
    branches:
      - master
      - datapakker
    paths:
      - '.github/workflows/datapakker.yml'
      - 'datapakker/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/datapakker/soknad:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('gradle.properties', 'settings.gradle.kts', '**/build.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: build
        uses: ./.github/actions/gradleBuild
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run: ./gradlew :datapakker:søknad:build
      - name: build
        uses: ./.github/actions/gradleBuildTest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login, Build and publish Docker image
        uses: ./.github/actions/loginBuildPublishDockerImage
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{env.IMAGE}}
          file: ./datapakker/søknad/Dockerfile

  deploy_to_dev:
    name: Deploy to dev
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: datapakker/søknad/nais.yml
          VARS: datapakker/søknad/nais-dev.json

  deploy_to_prod:
    name: Deploy to prod
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: datapakker/søknad/nais.yml
          VARS: datapakker/søknad/nais-prod.json