name: reusable workflow - Deployer til dev/test miljøet
description: kjører bare dersom det er master branchen

on:
  workflow_call:
    inputs:
      apikey:
        required: true
        type: string

jobs:
  deploy_to_dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ inputs.apikey }}
          CLUSTER: dev-fss
          RESOURCE: nais.yml
          VARS: nais-dev.json