name: reusable workflow - Deployer til dev/test miljøet
#description: kjører bare dersom det er master branchen

on:
  workflow_call:

jobs:
  deploy_to_dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais.yml
          VARS: nais-dev.json