name: Build and deploy to preprod on push to master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/datapakker.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/alerts-deploy.yml'
      - 'alerts.yml'
      - 'README.md'
      - 'docker-compose.yml'
      - 'datapakker/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/su-se-bakover:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Run gradle build
        uses: gradle/gradle-build-action@v2.8.0
        id: gradle-build
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          #arguments: --configuration-cache build
          arguments: build
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          pull: true
          tags: ${{env.IMAGE}}

  deploy_to_dev:
    name: Deploy to dev
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais.yml
          VARS: nais-dev.json

  generate-draft-release:
    name: Generate/update draft release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
