name: Build and deploy to preprod on push to master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/datapakker.yml'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/alerts-deploy.yml'
      - 'alerts.yml'
      - 'README.md'
      - 'docker-compose.yml'
      - 'datapakker/**'
      - 'local-db-scripts/**'
      - 'scripts/**'
      - '.editorconfig'
      - '.env*'

env:
  IMAGE: ghcr.io/${{ github.repository }}/su-se-bakover:${{ github.sha }}

jobs:
  build-test-push-image:
    name: Build, test and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        uses: ./.github/actions/build-and-test
      - name: Push image
        uses: ./.github/actions/push-image
        with:
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.sha }}
  submit-dependency-graph:
    needs: build-test-push-image
    name: Submit dependency graph
    permissions:
      contents: 'write'
    uses: navikt/su-se-bakover/.github/workflows/reusable-submit-dependency-graph.yml@master
  deploy-to-preprod:
    needs: build-test-push-image
    name: Deploy to preprod
    uses: navikt/su-se-bakover/.github/workflows/reusable-deploy.yml@master
    with:
      nav-environment: dev
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

#  generate-draft-release:
#    name: Generate/update draft release
#    runs-on: ubuntu-latest
#    permissions:
#      contents: 'write' # needed to create/edit releases
#      pull-requests: 'write' # needed to add labels to pull requests
#    steps:
#      # Drafts your next Release notes as Pull Requests are merged into "master"
#      - uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
