name: Build and deploy to preprod on push to master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/datapakker.yml'
      - 'datapakker/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/su-se-bakover:${{ github.sha }}

jobs:
  build-and-test:
    if: ${{contains(github.event.head_commit.message, '--skip_tests')}}
    uses: ./.github/workflows/build.yml
    with:
      withoutTests: ${{contains(github.event.head_commit.message, '--skip_tests')}}

  build-and-deploy-image:
    needs: build-and-test
    secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/loginBuildPublishDockerImage
        with:
          repo: ${{ github.repository }}
          image: ${{env.IMAGE}}

  deploy-to-dev :
    needs: build-and-deploy-image
    uses: ./.github/workflows/dev-deploy.yml
    secrets: inherit

  snyk:
    uses: ./.github/workflows/snyk.yml
    secrets: inherit

  generate-draft-release:
    name: Generate/update draft release
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}