name: Deploy

on:
  workflow_call:
    inputs:
      nav-environment:
        required: true
        description: 'dev or prod'
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true
        description: 'secrets.NAIS_DEPLOY_APIKEY'
jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          nav-environment: ${{ inputs.nav-environment }}
          NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
