name: Submit dependency graph

on:
  workflow_call:

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/submit-dependency-graph