name: Deploy

on:
  workflow_call:

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to ${{ inputs.environment }}
        uses: ./.github/actions/deploy
        with:
          NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          environment: ${{ inputs.environment }}
